plugins {
    id "com.android.application"
}

android {
    namespace "com.localcore"
    compileSdk 36
    ndkVersion "27.3.13750724"

    defaultConfig {
        applicationId "com.localcore"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0.0"

        ndk {
            abiFilters "arm64-v8a", "x86_64"
        }

        externalNativeBuild {
            cmake {
                arguments "-DCMAKE_OBJECT_PATH_MAX=250"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
            version "3.22.1"
            buildStagingDirectory "D:/cxx/LocalCore"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
}

